### ISSUE TITLE
C? This is C++...

### ISSUE THREAD

**Issue by kevyonan** [publicrepo/gmscript#5]
the README says that you can use GameMonkey in C but I don't see any way to interface GameMonkey with C, what's with the false advertisement?

There's not even a C interface here! What the hell?

**Comment by publicrepo** [comment]
Hi Assyrianic,

You are correct. That was unintentional false advertising. My apologies! At the time, us programmers often referred to C++ as 'C'. Certainty not trying to hide anything, the gmscript.com main web page says:

"What platforms does GameMonkey run on?
Written entirely in C++, it should run on any platform with at most minor modification or configuration.  ..."

I'll correct the documentation to reflect this.

Thank you for reporting. I hope you can find a C++ compiler to try GM, otherwise LUA may be the script for you.

Best regards!

**Comment by publicrepo** [comment]
Looking at the readme and web page, I believe you're mostly referring to the term "C/C++" "in C" "From C". I'll change those to just "C++" to avoid ambiguity and assumption since a C++ compiler is required unless wrapped and exported in a way not supplied here.
