### ISSUE TITLE
Is this the official version of GM script?

### ISSUE THREAD

**Issue by ell1e** [publicrepo/gmscript#6]
Is this the official version of GM script? The readme has this sentence: `This project is Greg's personal build of GM Script. It is primarily maintained for stability.` which sounds like it's a fork. But where is the official release available then? If this is the repo for the official code base, I would recommend rewording that sentence a little to be less misleading.

**Comment by publicrepo** [comment]
It is somewhat ambiguous. I'll update the description if I can think of a better one...

I'm one of the two main original creators of the GM project. I maintain this build mostly for stability. I have no time to implement new features. Some other branches, at various times, have implemented new features and surpassed it.  I have integrated a few of their features into my build.

Due to lack of time and support, I basically I don't want the responsibility of calling this an official version of GM, where one may expect to request features and receive support. That said, I'm happy to maintain this repo as a stable source and host a forum to facilitate user discussion.

The language is not abandoned as much as stagnant. Active developers come and go, use it for a project or few, perhaps add to it, then move on.  I'm currently using it to power an in-app debug console and perform some automated tests, so at least still building and using it a little.

So I'd suggest looking to see if any other branches exist (on github or elsewhere) that are more advanced or have features you desire. (It's been a while since I checked, to share any recommendation.) Otherwise grab my branch and make the most of it. It is at least a de-facto official version.

**Comment by ell1e** [comment]
That does sound a little like at least official future development beyond bugfixes has been somewhat abandoned. It would be worth pointing that out in the README and on the website, since right now they seem to dance around that issue which seems weird.

**Comment by publicrepo** [comment]
I've updated the readme visible from my branch. Hopefully this clarifies things a little.

**Comment by ell1e** [comment]
Thanks! That seems much clearer now
